server:
  port: 8091

spring:
  application:
    name: sc-order
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.80.132:8848

feign:
  httpclient:
    enabled: true # 使用apache http client替换feign默认的httpclient
