server:
  port: 7092

spring:
  application:
    name: sc-order
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.80.132:8848
        metadata:
          user:
            name: ${spring.security.user.name}  # 向注册中心注册本服务端点访问认证信息。这里不是配置访问客户端端点的认证信息，是本服务的
            password: ${spring.security.user.password}
            # management.context-path= # 访问地址，如果不是默认的actuator则需要配置
        username: nacos # nacos1.2以上版本增加客户端认证，需要认证才能读取配置
        password: vfc2020!@#
    sentinel:
      transport:
        port: 8791
        dashboard: localhost:8096 # sentinel console地址
        client-ip: localhost
    # spring cloud alibaba sentinel动态数据源配置参考：https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel
    # @see SentinelDataSourceHandler
      datasource:
        ds1: # sentinel 网关限流规则动态配置
          nacos:
            server-addr: 172.16.80.132:8848
            data-id: ${spring.application.name}-flow-rules
            group-id: SENTINEL_GROUP
            # 支持json、xml、custom. 使用custom时必须指定converter-class。
            data-type: json
            rule-type: flow
        ds2: # sentinel api组定义动态配置
          nacos:
            server-addr: 172.16.80.132:8848
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
            # 支持json、xml、custom. 使用custom时必须指定converter-class。
            data-type: json
            rule-type: degrade

  security:
    user: # http端点认证用户
      name: admin
      password: client2020#
management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露web方式访问的所有端点
    jmx:
      exposure:
        exclude: '*' # 关闭端点JMX访问方式
  endpoint:
    health:
      show-details: always
feign:
  httpclient:
    enabled: true # 使用apache http client替换feign默认的httpclient
  sentinel:
    enabled: true

ribbon:
  ReadTimeout: 4000 # feign客户端请求read time out设置





