server:
  port: 7093

druid-public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKdU10HP7aNZNvPjR/2bZlx3paIqefCSt3aLjIQdtgLNYla+T/I7UetNof7TymcX4eFuTO6OLiTIMD+jSzS5UTUCAwEAAQ==

spring:
  application:
    name: sc-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # com.p6spy.engine.spy.P6SpyDriver #com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # jdbc:p6spy:mysql://172.16.80.106:3306/vfc_sptsm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://172.16.80.106:3306/vfc_sptsm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: vfc_sptsm_qa
    password: ftETtJ/EDOIB4MpNwX8+M0ehP9g4XSzo9puATWjsAUzeZszdqW0Em5PruVhwb4ZNocUbduR2vN+IjKMnlBPeqg==
    druid:
      initial-size: 1
      # 启用数据库密码加密
      connection-properties: config.decrypt=true;config.decrypt.key=${druid-public-key}
      filter:
        stat:
          enabled: false
        wall:
          enabled: false
        slf4j:
          enabled: false
        log4j2:
          enabled: false
        log4j:
          enabled: false
        commons-log:
          enabled: false
        config: # 该配置要启用才能加密数据库密码
          enabled: true
      stat-view-servlet:
        enabled: false # 关闭监控
      web-stat-filter:
        enabled: false
        session-stat-enable: false

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.80.132:8848
        metadata:
          user:
            name: ${spring.security.user.name}  # 向注册中心注册本服务端点访问认证信息。这里不是配置访问客户端端点的认证信息，是本服务的
            password: ${spring.security.user.password}
            # management.context-path= # 访问地址，如果不是默认的actuator则需要配置
        username: nacos # nacos1.2以上版本增加客户端认证，需要认证才能读取配置
        password: vfc2020!@#
    sentinel:
      transport:
        port: 8791
        dashboard: localhost:8096 # sentinel console地址
        client-ip: localhost
      log:
        dir: /app/biz_logs/${spring.application.name}/csp # sentinel 日志目录
    # spring cloud alibaba sentinel动态数据源配置参考：https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel
    # @see SentinelDataSourceHandler
      datasource:
        ds1: # sentinel 网关限流规则动态配置
          nacos:
            server-addr: 172.16.80.132:8848
            data-id: ${spring.application.name}-flow-rules
            group-id: SENTINEL_GROUP
            # 支持json、xml、custom. 使用custom时必须指定converter-class。
            data-type: json
            rule-type: flow
        ds2: # sentinel api组定义动态配置
          nacos:
            server-addr: 172.16.80.132:8848
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
            # 支持json、xml、custom. 使用custom时必须指定converter-class。
            data-type: json
            rule-type: degrade

  security:
    user: # http端点认证用户
      name: admin
      password: client2020#
management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露web方式访问的所有端点
    jmx:
      exposure:
        exclude: '*' # 关闭端点JMX访问方式
  endpoint:
    health:
      show-details: always
feign:
  httpclient:
    enabled: true # 使用apache http client替换feign默认的httpclient
  sentinel:
    enabled: true

ribbon:
  ReadTimeout: 4000 # feign客户端请求read time out设置

ahas:
  namespace: default
  license: d86d37a37296462bb7dd11e688380540
project:
  name: ${spring.application.name}

mybatis-plus:
  mapper-locations: classpath*:com/zz/scorder/dao/mapper/**/*.xml



