spring:
  application:
    name: gc-gateway
  rabbitmq:
    host: 172.16.80.132
    port: 5672
    username: guest
    password: mq2019!

  # redis配置
  redis:
    password: jfyxow!22##
    host: 172.16.80.106
    port: 6379
  cloud:
    gateway:
      # 设置gateway转发到后台服务器的请求参数，超时时间等
      httpclient:
        response-timeout: PT5.1S
        connect-timeout: 5000


# 为特定hystrix命令设置超时时间。mycmd为对应的命令
hystrix.command.mycmd.execution.isolation.thread.timeoutInMilliseconds: 15000

logging:
  level:
    com.*: info
    org.*: info
    reactor.*: debug

nacos:
  config:
    server-addr: 172.16.80.132:8848
    group: sentinel:demo
    data-id: demo.gateway.flow.rule.yaml

server:
  port: 8086