# 公共配置
spring:
  cloud:
    nacos:
      config:
        server-addr: 172.16.80.153:8848
        namespace: cf892fd5-3440-4981-8cc4-73c0ab0d58c3
        file-extension: yaml
      #        # 读取多个配置文件
      #        extension-configs[0]:
      #          data-id: gateway.route.rule.yaml
      #          group: config.gateway
      #          refresh: true
      #      username: nacos # nacos1.2以上版本增加客户端认证，需要认证才能读取配置
      #      password: vfc2020!@#
      discovery:
        server-addr: 172.16.80.153:8848 # 服务注册，可以通过服务名转发
        namespace: cf892fd5-3440-4981-8cc4-73c0ab0d58c3
        #metadata:
        #  user:
        #     name: ${spring.security.user.name}  # 向注册中心注册本服务端点访问认证信息。这里不是配置访问客户端端点的认证信息，是本服务的
        #     password: ${spring.security.user.password}
            # management.context-path= # 访问地址，如果不是默认的actuator则需要配置

        watch:
          enabled: false # 是否开启NacosWatch,向spring boot admin刷新新注册的服务
        watch-delay: 10000 # Nacos watch执行时间间隔默认30s

    sentinel:
      transport:
        port: 8791 # 客户端服务为console开放的端口，如果端口占用会自动使用+1的端口，因此这里也可以配置成公用的
        dashboard: localhost:8096 # sentinel console地址
        client-ip: 192.168.5.37 # 指定本地sentinel客户端的IP，不要使用localhost

sentinel:
  server-addr: 172.16.80.153:8848
  namespace: cf892fd5-3440-4981-8cc4-73c0ab0d58c3