spring:
  cloud:
    gateway:
      # 设置gateway转发到后台服务器的请求参数，超时时间等
      httpclient:
        response-timeout: PT10.1S
        connect-timeout: 10000
    sentinel:
      filter: # 屏蔽URL资源，显示网关路由资源
        enabled: false

  security:
    user: # http端点认证用户
      name: admin
      password: client2020#
management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露web方式访问的所有端点
    jmx:
      exposure:
        exclude: '*' # 关闭端点JMX访问方式
  endpoint:
    health:
      show-details: always

ahas:
  namespace: default
  license:
    d86d37a37296462bb7dd11e688380540
project:
  name: ${spring.application.name}
