# db配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.80.106:3306/vfc_sptsm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: vfc_sptsm_qa
    # 生成的加密后的密码
    password: ftETtJ/EDOIB4MpNwX8+M0ehP9g4XSzo9puATWjsAUzeZszdqW0Em5PruVhwb4ZNocUbduR2vN+IjKMnlBPeqg==
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      # 启用数据库密码加密
      connection-properties: config.decrypt=true;config.decrypt.key=${druid-public-key}
      filter:
        stat:
          enabled: false
        wall:
          enabled: false
        slf4j:
          enabled: false
        log4j2:
          enabled: false
        log4j:
          enabled: false
        commons-log:
          enabled: false
        config: # 该配置要启用才能加密数据库密码
          enabled: true
      stat-view-servlet:
        enabled: false # 关闭监控
      web-stat-filter:
        enabled: false
        session-stat-enable: false

  cloud:
    # spring cloud alibaba sentinel动态数据源配置参考：https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel
    # @see SentinelDataSourceHandler
    sentinel:
      datasource:
        ds1: # sentinel 网关限流规则动态配置
          nacos:
            server-addr: 172.16.80.132:8848
            data-id: ${spring.application.name}-gateway-flow-rules
            group-id: SENTINEL_GROUP
            # 支持json、xml、custom. 使用custom时必须指定converter-class或bean。
            data-type: custom
            converter-class: gatewayFlowDecoder
            rule-type: gw-flow
        ds2: # sentinel api组定义动态配置
          nacos:
            server-addr: 172.16.80.132:8848
            data-id: ${spring.application.name}-api-definition
            group-id: SENTINEL_GROUP
            # 支持json、xml、custom. 使用custom时必须指定converter-class。
            data-type: custom
            converter-class: apiDefinitionDecoder
            rule-type: gw-api-group

      # @see com.alibaba.cloud.sentinel.gateway.scg.SentinelSCGAutoConfiguration
      scg:
        order: -1  # sentinel filter执行顺序，越小越优先不能超过GlobalRequestFilter的执行顺序

      log:
        dir: /app/biz_logs/${spring.application.name}/csp # sentinel 日志目录
      metric:
        fileTotalCount: 10
        file-single-size: 1024 * 1024 * 200 # 单个sentinel metric文件大小，200M
      transport:
        port: 8791
        dashboard: localhost:8096 # sentinel console地址
        client-ip: localhost # 指定本地sentinel客户端的IP

    nacos:
      discovery:
        server-addr: 172.16.80.132:8848 # 服务注册，可以通过服务名转发
        metadata:
          user:
            name: ${spring.security.user.name}  # 向注册中心注册本服务端点访问认证信息。这里不是配置访问客户端端点的认证信息，是本服务的
            password: ${spring.security.user.password}
            # management.context-path= # 访问地址，如果不是默认的actuator则需要配置

        watch:
          enabled: false # 是否开启NacosWatch,向spring boot admin刷新新注册的服务
        watch-delay: 10000 # Nacos watch执行时间间隔默认30s

    gateway:
      route:
        nacos:
          server-addr: 172.16.80.132:8848
          data-id: sc-alibaba-gateway-gateway-route-rules
          group-id: SENTINEL_GROUP
          # 支持json、xml、custom. 使用custom时必须指定converter-class或bean。
          converter-class: routeRuleDecoder

#    gateway:
#      discovery:
#        locator:
#          enabled: true  # 开启DiscoveryClient gateway integration。自动配置服务注册中心的所有服务列表的路由。对外网关不需要开启这个
#          url-expression: "'lb://' + serviceId" # 路由的目标地址的表达式，默认为 "'lb://' + serviceId"。lb://标识开启负载均衡

druid-public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKdU10HP7aNZNvPjR/2bZlx3paIqefCSt3aLjIQdtgLNYla+T/I7UetNof7TymcX4eFuTO6OLiTIMD+jSzS5UTUCAwEAAQ==

# logback-spring.xml中使用到的属性
LOG_BASE: /app/biz_logs/${spring.application.name}

# logback profile 配置
logging:
  config: classpath:logback-spring.xml

