spring:
  cloud:
    gateway:
      # 设置gateway转发到后台服务器的请求参数，超时时间等
      httpclient:
        response-timeout: PT20.1S
        connect-timeout: 10000
    sentinel:
      filter:
        enabled: false

  profiles:
    # maven变量，打包时会被替换成相应的profile。如果需要本地启动，则需要修改为对应的profile
    # 这里的profile激活只用于本地启动，实际线上环境会使用启动参数激活profile
    active: local #@profileActive@

  security:
    user: # http端点认证用户
      name: admin
      password: client2020#
management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露web方式访问的所有端点
    jmx:
      exposure:
        exclude: '*' # 关闭端点JMX访问方式
  endpoint:
    health:
      show-details: always

server:
  port: 8087